server:
  port: 8888
  
spring:
  application:
    name: demo-config-svc
  profiles:
    active: native  
  cloud:
    config:
      server:
        bootstrap: false
        #prefix: /config
        native:
          searchLocations: file:./config/
          addLabelLocations: false
          
management:
#  info:
#    git:
#      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${random.value}
#    hostname: localhost.jk.com